[package]
name = "lykil-studio"
description = "Lykil Studio: manage Lykil keyboards"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
publish = false

[dependencies]
aurea = { git = "https://github.com/SkuldNorniern/aurea" }
lykil = { path = "../lykil" }
lykil-config = { path = "../lykil/lykil-config" }
lykil-device = { path = "../lykil/lykil-device" }
sys-locale = "0.3"
lykil-protocol = { path = "../lykil/lykil-protocol", features = ["std"] }
lykil-qmk = { path = "../lykil/lykil-qmk", features = ["import"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }

[target."cfg(windows)".dependencies]
windows = { version = "0.62.2", features = ["Devices_Lights", "Devices_Enumeration", "Foundation", "Foundation_Collections", "Foundation_Numerics", "UI"] }
windows-future = "0.3.2"
